WillBlog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'welcome#home'
get 'about', to: 'welcome#about'

resources :articles


















end

WillBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

WillBlog/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum:3, maximum:50}
  validates :description, presence: true, length: {minimum:10, maximum:300}
end

WillBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

WillBlog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Successfully updated"
      redirect_to article_path
    else
      render 'edit'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = "Successfully created..."
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Successfully deleted"
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :description)
    end

end

WillBlog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


end

WillBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

WillBlog/app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevented the article from getting created</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |a| %>
  <p>
    <%= a.label :title %> <br/>
    <%= a.text_field :title %>
  </p>
  <p>
    <%= a.label :description %> <br/>
    <%= a.text_area :description %>
  </p>
  <p>
    <%= a.submit %>
  </p>

<% end %>

<%= link_to "Back to all the articles", articles_path %>

WillBlog/app/views/articles/edit.html.erb
<h1>Editing the selected article</h1>

<%= render "form" %>

WillBlog/app/views/articles/index.html.erb
<h1>List of articles</h1>
<p>
  <%= link_to "Create a new article", new_article_path %>
</p>
<table>
  <tr>
    <th>Title</th>
    <th>Desciption</th>
  </tr>

  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to "Edit", edit_article_path(article) %></td>
    <td><%= link_to "Show", article_path(article) %></td>
    <td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>
<p>
<%= link_to 'Back to Homepage', root_path %>
</p>

WillBlog/app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render "form" %>

WillBlog/app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>
  Title: <%= @article.title %>
</p>

<p>
  Description: <%= @article.description %>
</p>

<%= link_to "Edit", edit_article_path(@article) %> |
<%= link_to "Back to all the articles", articles_path %>

WillBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WillBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

WillBlog/app/views/welcome/about.html.erb
<h1>This is the About Page</h1>

<p>This was created with Ruby on rails 5.2 by WillChnL (-.-)</p>

<%= link_to 'Go back to Home', root_path %>

WillBlog/app/views/welcome/home.html.erb
<h1>This is the HomePage</h1>

<%= link_to 'Will Blog', articles_path %> | <%= link_to 'go to About', about_path %>